#!/bin/bash

cd /var/www/MyShell/
sudo -s git pull

#vagrantのgitアカウントの設定
USERNAME="`git config --global --list | grep user.name`"
USERMAIL="`git config --global --list | grep user.email`"

if [ "$USERNAME" = "" ] ; then
	echo "Gitのアカウント名を指定してください。"
	echo -n "> "
	read INPUT_USERNAME
	if [ ! "$INPUT_USERNAME" = "" ] ; then
		git config --global user.name "$INPUT_USERNAME"
	fi
fi

if [ "$USERMAIL" = "" ] ; then
	echo "Gitのメールアドレスを指定してください。"
	echo -n "> "
	read INPUT_USERMAIL
	if [ ! "$INPUT_USERMAIL" = "" ] ; then
		git config --global user.email "$INPUT_USERMAIL"
	fi
fi

cd /var/www/MyShell/install
sudo -s bash install.sh $1
